project:
  type: book
  output-dir: docs

book:
  title: "파이썬으로 데이터 분석하기"
  author: "느리게"
  date: "2025. 12. 28."
  chapters:
    - index.qmd
    - part: "데이터 처리"
      chapters: 
        - data_load_save.qmd
    - part: "기계학습"
      chapters:
        - regression.qmd
        - classification.qmd
    - part: "부록"
      chapters:
        - references.qmd

bibliography: references.bib

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand



