project:
  type: book
  output-dir: _site

metadata:
  google-site-verification: "8xHzi-r2KaeozfPyDbwq2rtYE8sEI8Xu6irhM0ccwBU"
  keywords: ["python", "파이썬", "numpy", "넘파이", "넘피", "pandas", "판다스", "machine learning", "기계학습", "머신러닝", "회귀", "분류", "군집"]

book:
  title: "데이터 분석 (파이썬)"
  author: "느리게"
  date: last-modified
  repo-url: https://github.com/yeonkyupark/dawithpython 
  repo-branch: main
  repo-actions: [edit]
  favicon: logo.png
  page-footer: 
    left: "Copyright(c) 2026 YK" 
    right: "Data Analytics with Python"
  sidebar: 
    tools:
      - icon: instagram
        href: https://www.instagram.com/yeonkyu.park/
      - icon: globe
        href: https://yeonkyupark.github.io/
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "I. 데이터 처리"
      chapters: 
        - DP10_data_load_save.qmd      # 데이터 적재
        - DP20_data_cleaning.qmd       # 데이터 정제
        - DP30_data_reshape.qmd        # 데이터 변형
        - DP40_data_transform.qmd      # 데이터 변환
        - DP50_feature_selection.qmd   # 변수선택
    - part: "II. 가설검정"
      chapters:
        - HT10_hypothesis_test.qmd     # 가설검정
    - part: "III. 기계학습"
      chapters:
        - ML10_regression.qmd          # 회귀분석
        - ML20_classification.qmd      # 분류분석
        - ML30_clustering.qmd          # 군집분석
    - part: "부록"
      chapters:
        - references.qmd

bibliography: references.bib

number-sections: false

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
    include-in-header: adsense.html
    include-after-body: adsense-body.html


toc: true
toc-depth: 4
toc-title: 목차

execute:
  warning: false
  message: false