project:
  type: book
  output-dir: _site

metadata:
  google-site-verification: "8xHzi-r2KaeozfPyDbwq2rtYE8sEI8Xu6irhM0ccwBU"
  keywords: ["python", "파이썬", "numpy", "넘파이", "넘피", "pandas", "판다스", "machine learning", "기계학습", "머신러닝", "회귀", "분류", "군집"]

book:
  title: "데이터 분석 (파이썬)"
  author: "느리게"
  date: last-modified
  repo-url: https://github.com/yeonkyupark/dawithpython 
  repo-branch: main
  repo-actions: [edit]
  favicon: logo.png
  page-footer: 
    left: "Copyright(c) 2026 YK" 
    right: "Data Analytics with Python"
  sidebar: 
    tools:
      - icon: instagram
        href: https://www.instagram.com/yeonkyu.park/
      - icon: globe
        href: https://yeonkyupark.github.io/
    collapse-level: 2
  chapters:
    - index.qmd
    - part: "I. 데이터 처리"
      chapters: 
        - data_load_save.qmd
    - part: "II. 기계학습"
      chapters:
        - regression.qmd
        - classification.qmd
    - part: "부록"
      chapters:
        - references.qmd

bibliography: references.bib

number-sections: false

format:
  html:
    css: styles.css
    theme:
      - cosmo
      - brand
    include-in-header: adsense.html
    include-after-body: adsense-body.html


toc: true
toc-depth: 4
toc-title: 목차
